version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gdp_sa
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"